### PR TITLE
WIP: Add Nan's Prophet Intro Slides.

### PR DESCRIPTION
**Pull request by ClaytonJY**

### CODE REVIEW

**Comment by ClaytonJY** [comment]
@V3g4 let us know if you update your slides, and I'll update this PR

**Comment by V3g4** [comment]
@ClaytonJY @ellisvalentiner Updated the slides with some changes (including fixing an error and some cleanup of order and format).

**Comment by ellisvalentiner** [comment]
@V3g4 slides look pretty good -- very excited for Thursday. Can I suggest adding an About Me slide and/or a slide at the end with your contact info in case anyone wants to follow up with you?

**Review by ellisvalentiner — APPROVED** [review]

**Comment by V3g4** [comment]
@ellisvalentiner Thanks for reviewing the slides! I just added a page at the end with contact info (just my slack id which is the best way to reach me anyway :-) )

**Pull request merged**
