### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by kraigrs**

### CODE REVIEW

**Comment by ClaytonJY** [comment]
So I was only expecting to see an `Rmd`, an `html`, and the `png` figures. What is everything else, the other R files, the python file, binary files, etc?

I think the figures (`png`'s) should be in their own directory, to make this more organized. That means you'll have to update your references to them in the Rmd.

**Comment by kraigrs** [comment]
Those other R files are basically working scripts before I made the Rmd,
would you like me to get rid of them? And all of the PNG figures should be
in a directory called /figs

The Python script and the binary file is for word2vec, but that doesn't
impact the Rmd at all, just mainly for everyone's reference.

Let me know if you just want the Rmd, HTML, and /figs directory and I'll
update.

On Wed, Sep 9, 2015 at 11:33 AM, Clayton notifications@github.com wrote:

> So I was only expecting to see an Rmd, an html, and the png figures. What
> is everything else, the other R files, the python file, binary files, etc?
> 
> I think the figures (png's) should be in their own directory, to make
> this more organized. That means you'll have to update your references to
> them in the Rmd.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnnArborRUserGroup/Presentations/pull/22#issuecomment-138948548
> .

## 

Kraig Stevenson, Ph.D.
Data Scientist

Data Governance & Research
Trinity Health
20555 Victor Parkway
Livonia, MI 48152-7018

**Comment by ClaytonJY** [comment]
You're right about `figs/`, totally missed that.

Scrap the non-final R scripts; sounds like anything of value there is also in the Rmd.

Will you be talking about the Python and binary file in the talk? If yes, leave em. If no, but you still think they're useful, leave them but move them into a subdirectory.

What about the text files?

**Comment by kraigrs** [comment]
The text file is necessary as I can only make a certain number of API calls
to musixmatch per day, so for testing purposes and making the presentation,
I made the API calls and output the text file and in the Rmd that text file
is imported.

On Wed, Sep 9, 2015 at 12:11 PM, Clayton notifications@github.com wrote:

> You're right about figs/, totally missed that.
> 
> Scrap the non-final R scripts; sounds like anything of value there is also
> in the Rmd.
> 
> Will you be talking about the Python and binary file in the talk? If yes,
> leave em. If no, but you still think they're useful, leave them but move
> them into a subdirectory.
> 
> What about the text files?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnnArborRUserGroup/Presentations/pull/22#issuecomment-138959380
> .

## 

Kraig Stevenson, Ph.D.
Data Scientist

Data Governance & Research
Trinity Health
20555 Victor Parkway
Livonia, MI 48152-7018

**Comment by ClaytonJY** [comment]
Ah okay, that makes sense. Remove the old files and remove or move the "extra" stuff in a new commit, push it, and I'll approve.

**Comment by kraigrs** [comment]
OK, I cleaned things up a bit.

**Comment by ClaytonJY** [comment]
Ok so now I'm looking at it on [rawgit](https://rawgit.com/kraigrs/Presentations/master/2015-09/lyricsNLP/lyricsNLP.html) and notice the following:
- page numbers work in chrome! I am on a different machine than I was this morning, though
- TOOL album art is cutoff (slide 5); doesn't bother me much, you can edit or just leave it
- word cloud code still looks good to me (@ellisvalentiner, does the rawgit-hosted slide still look bad on your machine?)
- formulas; do you want to make them LaTeX or nah?

**Comment by ellisvalentiner** [comment]
The word cloud code is still obscured on my machine. Not sure what is causing it.

screen shot 2015-09-09 at 1 50 47 pm

**Comment by kraigrs** [comment]
Nah, it's really just those couple lines, and I mistakenly had put log2
instead of log, so now there's no need to subscript.

Could it have something to do with the fact that I tried to make that slide
have 2 columns?

On Wed, Sep 9, 2015 at 1:36 PM, Clayton notifications@github.com wrote:

> Ok so now I'm looking at it on rawgit
> https://rawgit.com/kraigrs/Presentations/master/2015-09/lyricsNLP/lyricsNLP.html
> and notice the following:
> - page numbers work in chrome! I am on a different machine than I was
>   this morning, though
> - TOOL album art is cutoff (slide 5); doesn't bother me much, you can
>   edit or just leave it
> - word cloud code still looks good to me (@ellisvalentiner
>   https://github.com/ellisvalentiner, does the rawgit-hosted slide
>   still look bad on your machine?)
> - formulas; do you want to make them LaTeX or nah?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnnArborRUserGroup/Presentations/pull/22#issuecomment-138985940
> .

## 

Kraig Stevenson, Ph.D.
Data Scientist

Data Governance & Research
Trinity Health
20555 Victor Parkway
Livonia, MI 48152-7018

**Comment by ClaytonJY** [comment]
Ok, I'm fine to merge now, but I have no idea what's causing those issues for Ellis. I'll leave it up to you to merge or not @ellisvalentiner.

**Pull request merged**
