### PR TITLE
Upload 7/9 Arules Presentations

### PR DESCRIPTION
**Pull request by brandonstange**

### CODE REVIEW

**Comment by ellisvalentiner** [comment]
Getting an error when sourcing `2_RuleGen.R`

```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("rapriori", items@p, items@i, items@Dim, parameter, control,     appearance, data@itemInfo, PACKAGE = "arules")
 2: apriori(sm2, parameter = list(minlen = 1, supp = 0.008, conf = 0.4,     maxlen = 4), appearance = list(rhs = outcomelist, none = "Pass or Not Critical",     default = "lhs"), control = list(verbose = T))
 3: eval(expr, envir, enclos)
 4: eval(ei, envir)
 5: withVisible(eval(ei, envir))
 6: source("2_RuleGen.R", encoding = "UTF-8")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

To be fair I'm running RRO 3.2.0, so this could be a problem with Revolution Analytics more than the actually code. @ClaytonJY can you take a look at this and see if you can compile the Rmd on your machine?

My session info:

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] fortunes_1.5-2
```

**Comment by brandonstange** [comment]
I'm running RPRO as well.  Do you have the arules and arulesVis packages installed?  I should probably add a requirements readme or something.  The errors can be a bit cryptic since I'm sourcing scripts from the markdown file.  Here's my info:

R version 3.2.0 (2015-04-16)
 Platform: x86_64-w64-mingw32/x64 (64-bit)
 Running under: Windows Server 2012 x64 (build 9200)

 attached base packages:
 [1] grid      stats     graphics  grDevices utils     datasets  methods  
 [8] base     

 other attached packages:
 [1] arulesViz_1.0-0 arules_1.1-6    Matrix_1.2-0    tidyr_0.2.0  
 [5] readr_0.1.1     dplyr_0.4.2

**Comment by ellisvalentiner** [comment]
I have both packages installed.

Sourcing `1_DataPrep.R` also returns a warning:

```
Warning message:
268 problems parsing 'https://data.cityofnewyork.us/api/views/xx67-kt59/rows.csv?accessType=DOWNLOAD'. See problems(...) for more details. 
```

**Comment by brandonstange** [comment]
Okay, I think this one will work.  It was originally done on a pretty hefty server.  When I pulled it down to my personal laptop R was crashing.  I changed the analysis a bit to make it less resource intense.  Would you give this one a shot?  Thanks.

Edit:  Oh and the warnings are just data format issues picked up by readr... Trailing whitespace and stuff.  They don't impact results.

**Comment by dynamics77** [comment]
I was able to compile R Markdown document with no issues.

**Comment by ellisvalentiner** [comment]
I'm on my phone and can't check well, but didn't I already merge it in?

**Pull request merged**
